
model:
    name: "mit_b0" # ["mit_b0", "mit_b3", "unet_resnet34", "deeplab_v3plus"]
    in_channels: 6
    proj_dim: 128
    num_classes: 2
    load_path: "/kaggle/input/models/orangeggnt/bilk-epochs/pytorch/default/3/bilk_2GPU_model_epoch_2th"
    best_path: "/kaggle/working/bilk_fewshot_random_best.pth"
    last_path: "/kaggle/working/bilk_fewshot_random_last.pth"

dataset:
    name: "Sen1Floods11" # ["Sen1Floods11", "Cityscapes", "Landsat8_Cloud", "Pascal_VOC2012"]
    num_classes: 2

criterion:
    ignore_index: -1

hyperparams:
    seed : 42
    batch_size : 6
    learning_rate : 0.00005 
    LAMBDA : 0.5 # [0.1, 0.5, 1, 2, 5]
    epochs : 60

